-- Migration: Seed demonstration data for CMS
-- Created: 2026-04-06
-- Purpose: Populate CMS tables with demonstration data for testing and showcasing

INSERT INTO cms_events (title, description, start_date, end_date, location, category, image_url, is_published, position) VALUES
('We Love Eya 2026', 'Festival culturel et artistique célébrant la diversité de la Côte d''Or. We Love Eya est le plus grand festival culturel annuel de Cotonou, réunissant artistes, musiciens et danseurs du Bénin et d''Afrique de l''Ouest.', '2026-04-15 18:00:00+00', '2026-04-18 02:00:00+00', 'Plage de Cotonou, Bénin', 'culture', 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800', true, 1),
('Vodoun Days - Festival du Vaudou', 'Célébration annuelle des traditions spirituelles et culturelles du vaudou. Les Vodoun Days célèbrent le patrimoine spirituel et culturel du Bénin avec processions, ateliers, expositions d''art et performances musicales.', '2026-05-10 08:00:00+00', '2026-05-12 22:00:00+00', 'Temple de Ouidah, Bénin', 'spirituel', 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800', true, 2),
('Concert Anniversaire Vano Baby - 10 ans', 'Un concert exceptionnel pour célébrer une décennie d''innovations musicales. Rejoignez Vano Baby pour un concert monumental avec performances en direct et surprises spéciales.', '2026-06-20 20:00:00+00', '2026-06-20 23:30:00+00', 'Stade de Cotonou, Bénin', 'musique', 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=800', true, 3),
('Speed Dating Professionnel', 'Événement de networking accéléré pour entrepreneurs et professionnels. Une approche innovante combinant speed dating et rencontres d''affaires organisée par des leaders du secteur privé.', '2026-05-25 18:00:00+00', '2026-05-25 21:00:00+00', 'Hôtel Sofitel Cotonou, Bénin', 'professionnel', 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800', true, 4),
('Forum International d''Innovations', 'Plateforme majeure réunissant entrepreneurs, innovateurs et investisseurs pour explorer les solutions technologiques. Thèmes: IA, fintech, énergies renouvelables, smart cities, santé numérique.', '2026-07-08 09:00:00+00', '2026-07-11 18:00:00+00', 'Centre de Conférences Internationaliste, Cotonou', 'innovation', 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800', true, 5),
('Festival du Film Africain', 'Célébration du cinéma africain avec projections de 80+ films, masterclasses avec réalisateurs, table-rondes et gala d''ouverture. Découvrez les meilleures productions du continent.', '2026-08-05 17:00:00+00', '2026-08-12 23:59:00+00', 'Cinémas divers à Cotonou, Bénin', 'culture', 'https://images.unsplash.com/photo-1489599849228-bed96d3a05c9?w=800', true, 6),
('Conférence de Santé et Bien-être', 'Conférence dédiée à la promotion de la santé et du bien-être en Afrique de l''Ouest. Sujets: santé maternelle, maladies chroniques, santé mentale, nutrition, fitness et médecine traditionnelle.', '2026-06-10 08:30:00+00', '2026-06-12 17:00:00+00', 'Hôtel Novotel Cotonou, Bénin', 'sante', 'https://images.unsplash.com/photo-1631217314997-e94188a1ce53?w=800', true, 7),
('Grand Marché Culturel Artisanal', 'Événement mensuel célébrant le talent des artisans béninois. Textiles, sculptures, bijoux, poteries, peintures, objets de décoration et produits cosmétiques naturels à découvrir.', '2026-05-16 10:00:00+00', '2026-05-17 20:00:00+00', 'Galerie d''Art de Cotonou, Bénin', 'artisanat', 'https://images.unsplash.com/photo-1578324568222-121067eb98d5?w=800', true, 8),
('Marathon Solidaire', 'Marathon annuel combinant le sport et la solidarité pour soutenir l''éducation des enfants défavorisés. Parcours variés: 42.195km, 21km, 10km et 5km pour enfants.', '2026-04-25 06:00:00+00', '2026-04-25 14:00:00+00', 'Stade de Cotonou - Parcours en ville', 'sport', 'https://images.unsplash.com/photo-1552674605-5defe6aa44bb?w=800', true, 9),
('Sommet du Tourisme Africain', 'Événement majeur réunissant ministres, hôteliers et tour-opérateurs pour développer le secteur touristique. Thèmes: tourisme durable, balnéaire, culturel, agritourisme et digital.', '2026-09-20 08:00:00+00', '2026-09-23 18:00:00+00', 'Centro Hotel Cotonou, Bénin', 'tourisme', 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800', true, 10)
ON CONFLICT DO NOTHING;

INSERT INTO cms_news (title, excerpt, content, image_url, is_featured, is_published, position) VALUES
('Partenariat stratégique avec le Forum International d''Innovations', 'Les étudiants de ESGIS auront accès à des rencontres exclusives avec les innovateurs et entrepreneurs du continent.', 'ESGIS Campus est fière d''annoncer un partenariat stratégique avec les organisateurs du Forum International d''Innovations. Les étudiants pourront participer aux pitch competitions, accéder aux conférences et ateliers, et bénéficier de mentorship avec des entrepreneurs confirmés.', 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800', true, true, 1),
('Nouvelles bourses d''études disponibles', 'ESGIS Campus lance un programme de bourses en partenariat avec des entreprises locales et internationales.', 'ESGIS Campus annonce le lancement d''un programme de bourses d''études destinées aux étudiants méritants mais aux moyens financiers limités. Les bourses couvrent les frais de scolarité, livres, matériel pédagogique et accès à tous les clubs et activités parascolaires.', 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800', true, true, 2),
('Les étudiants brillent au Vodoun Days Festival', 'Une délégation de 50 étudiants a brillé au festival avec un projet innovant sur la spiritualité et la technologie.', 'Une délégation de 50 étudiants de ESGIS Campus a brillé au Vodoun Days Festival, présentant un projet innovant explorant la convergence entre les traditions spirituelles béninoises et les technologies modernes. Les étudiants ont reçu des félicitations et des propositions de collaboration.', 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800', false, true, 3)
ON CONFLICT DO NOTHING;

INSERT INTO cms_announcements (title, content, priority, target_audience, is_published, position) VALUES
('Calendrier académique 2026-2027', 'Le calendrier académique pour l''année 2026-2027 a été finalisé. Ouverture: 1er septembre 2026. Fermeture: 30 juin 2027. Vacances académiques: 15 décembre - 15 janvier.', 'high', 'students', true, 1),
('Réunion d''information: Activités parascolaires', 'Tous les nouveaux étudiants sont invités à une réunion d''information le vendredi 12 avril à 14h. Découvrez les clubs disponibles: sports, culture, technologie, entrepreneuriat.', 'medium', 'students', true, 2),
('Plateforme d''orientation maintenant active', 'La nouvelle plateforme d''orientation en ligne est disponible pour tous les étudiants. Prenez des rendez-vous avec les conseillers, consultez les fiches des métiers, trouvez des stages et emplois.', 'normal', 'students', true, 3)
ON CONFLICT DO NOTHING;

INSERT INTO cms_banners (title, subtitle, image_url, cta_link, cta_text, background_color, text_color, is_active, position) VALUES
('We Love Eya 2026', 'Le plus grand festival culturel de Cotonou vous attend!', 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200', '/events', 'En savoir plus', '#667eea', '#ffffff', true, 1),
('Forum International d''Innovations', 'Rencontrez les entrepreneurs et innovateurs du continent', 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200', '/events', 'S''inscrire maintenant', '#f093fb', '#ffffff', true, 2),
('ESGIS Campus: Mission transformatrice', 'Former les leaders de demain pour transformer l''Afrique', 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1200', '/about', 'Découvrir ESGIS', '#4facfe', '#ffffff', true, 3)
ON CONFLICT DO NOTHING;
